apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kqebxanbw-java-springboot
  janus-idp.io/tekton: kqebxanbw-java-springboot
  backstage.io/kubernetes-id: kqebxanbw-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kqebxanbw-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
